Error happened on: Sun Apr 19 15:24:58 CEST 2020-------------- Failed Components -------------- 
1. Process
-------------- Stack Traces -------------- 
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.julielab.jcore.consumer.xmi.XMIDBWriter.batchProcessComplete(XMIDBWriter.java:1017)
	at de.julielab.jcore.consumer.xmi.XMIDBWriter.process(XMIDBWriter.java:553)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:411)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.innerCall(PrimitiveAnalysisEngine_impl.java:329)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:321)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:271)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.processNext(ProcessingUnit.java:895)
	at org.apache.uima.collection.impl.cpm.engine.ProcessingUnit.run(ProcessingUnit.java:575)
Caused by: de.julielab.jcore.consumer.xmi.XmiDataInsertionException: de.julielab.costosys.dbconnection.util.CoStoSysSQLRuntimeException: java.sql.BatchUpdateException: Batch entry 7 INSERT INTO _data_xmi.documents (cord_id,base_document,max_xmi_id,sofa_mapping,document_text_sha256) VALUES ('0ht2ap9g',?,27,'1=_InitialView','5kp4P2OnvwCQ/2qUgaUVRLwgfZNIn+GSJe1qzNuRehw=') was aborted: ERROR: duplicate key value violates unique constraint "_data_xmidocuments_pkey"
  Detail: Key (cord_id)=(0ht2ap9g) already exists.  Call getNextException to see other errors in the batch.
	at de.julielab.jcore.consumer.xmi.XmiDataInserter.sendXmiDataToDatabase(XmiDataInserter.java:179)
	at de.julielab.jcore.consumer.xmi.XMIDBWriter.batchProcessComplete(XMIDBWriter.java:1005)
	... 12 more
Caused by: de.julielab.costosys.dbconnection.util.CoStoSysSQLRuntimeException: java.sql.BatchUpdateException: Batch entry 7 INSERT INTO _data_xmi.documents (cord_id,base_document,max_xmi_id,sofa_mapping,document_text_sha256) VALUES ('0ht2ap9g',?,27,'1=_InitialView','5kp4P2OnvwCQ/2qUgaUVRLwgfZNIn+GSJe1qzNuRehw=') was aborted: ERROR: duplicate key value violates unique constraint "_data_xmidocuments_pkey"
  Detail: Key (cord_id)=(0ht2ap9g) already exists.  Call getNextException to see other errors in the batch.
	at de.julielab.costosys.dbconnection.DataBaseConnector.importFromRowIterator(DataBaseConnector.java:2463)
	at de.julielab.costosys.dbconnection.DataBaseConnector.executeAndCommitUpdate(DataBaseConnector.java:2666)
	at de.julielab.costosys.dbconnection.DataBaseConnector.updateFromRowIterator(DataBaseConnector.java:2595)
	at de.julielab.jcore.consumer.xmi.XmiDataInserter.sendXmiDataToDatabase(XmiDataInserter.java:171)
	... 13 more
Caused by: java.sql.BatchUpdateException: Batch entry 7 INSERT INTO _data_xmi.documents (cord_id,base_document,max_xmi_id,sofa_mapping,document_text_sha256) VALUES ('0ht2ap9g',?,27,'1=_InitialView','5kp4P2OnvwCQ/2qUgaUVRLwgfZNIn+GSJe1qzNuRehw=') was aborted: ERROR: duplicate key value violates unique constraint "_data_xmidocuments_pkey"
  Detail: Key (cord_id)=(0ht2ap9g) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:145)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2184)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:481)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:840)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1538)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at de.julielab.costosys.dbconnection.DataBaseConnector.importFromRowIterator(DataBaseConnector.java:2442)
	... 16 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "_data_xmidocuments_pkey"
  Detail: Key (cord_id)=(0ht2ap9g) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	... 22 more

